### ISSUE TITLE
Moveaim mode "Decouple Look/Move" should follow cursor, not GUI position

### ISSUE THREAD

**Issue by feilen** [mabrowning/minecrift#139]
When using the Decouple Look/Move (which I've always found a bit more immersive as you can glance around as you walk without running yourself off a cliff) your movements follows the location of your GUI (which is as stated in the directions). However, in other games implementing this control, the keyhole has no impact on your body movement, and your body actually just directly follows wherever your cursor is pointing. In Minecrift, in order to slightly adjust which way you're walking, you need to drag the cursor all the way to the edge of the keyhole and nudge yourself in that direction. This makes slight adjustments (when running down a long narrow bridge, for example) very difficult. 

If someone does really like the 'with gui' option, it'd probably be best to add a third 'with cursor' option.

**Comment by StellaArtois** [comment]
So basically, an option that means you move forward in the direction of
the current cursor position?

**Comment by feilen** [comment]
Yep!

**Comment by StellaArtois** [comment]
Ok!

**Comment by feilen** [comment]
If it's something complicated to implement, I could look at doing it. Not totally certain how to set up a development environment for it, but I could give it a shot!

**Comment by feilen** [comment]
Okay, I've got Minecrift building and running out of eclipse. I'll see if I
can't implement something myself.

**Comment by feilen** [comment]
Wow, surprisingly easy to make the change! I'm going to go a step further
though and integrate it as a third option. Just give me an hour or so.

**Comment by StellaArtois** [comment]
Great!

Have a look in EntityRenderer.updatePositionAndOrientation() - look and aim
vectors are handled there.

Also the lookaimcontroller is where cursor direction is setup. This calls
down into com.mtbs.minecrift.control.aim - this is where I've tried to
unify the control scheme in 1.8, compared to 1.7. Any additional look aim
mode should probably go in here ideally.

VrSettings is where any new config params go. These can be accessed from
the GUI dialogs - see all the other settings for examples...

**Comment by StellaArtois** [comment]
Blimey I'm too slow! :-)

**Comment by feilen** [comment]
Aha! I've got one potential problem more related to source control than
anything. When I run 'getchanges.py' and run a git diff over the patches/
dir, the apparent changes are absolutely massive. Is this normal?

When I try to run my game in single-player mode it crashes when trying to
load the world too (although it works fine on multiplayer) so I suspect
some of those 'changes' are not at all genuine. Do you have any advice for
handling that?

**Comment by StellaArtois** [comment]
Hmm, no - you should only get the files changed in the diff. Have the line
endings been changed?

**Comment by feilen** [comment]
Line endings possibly have been changed, but git typically ignores that. It seems like whole chunks of code are minorly edited. Am I supposed to be doing this against 1.8? I'm on the port_to_1_8_1 branch.

**Comment by StellaArtois** [comment]
That all sounds ok, branch wise. Is your editor auto formatting the code or
similar?

**Comment by feilen** [comment]
That could be Eclipse doing that, but it shouldn't. I'll try again and
re-apply my changes, see what happens.

**Comment by feilen** [comment]
What version of the JDK are you using?

**Comment by StellaArtois** [comment]
I tend to use JDK 1.6. (0.45) still. Have the Minecraft min requirements changed to 1.7 yet?

**Comment by feilen** [comment]
No, but my Linux distribution doesn't have Java that goes back that far.
Might have an impact on the decompiling process. I'll figure something out.

**Comment by feilen** [comment]
Switched over to JDK6. I'm almost certain it's a platform-specific line endings (windows is CRLF, other platforms are LF) But it's kind of random which is which. Can you check for those?

(git should be able to detect them)

I think I may be able to switch everything to \n and see what happens

**Comment by feilen** [comment]
No luck. Have you got a working copy of the source (from install.py) that I can use? The output I'm getting is apparently mildly different (which results in a lot of garbage patch changes)

**Comment by StellaArtois** [comment]
Having the same issues now I'm testing on a Mac (finally!). I'll look into it. They all need to be normalised to LF.

**Comment by feilen** [comment]
Keep me posted!

**Comment by feilen** [comment]
I tried to create a clean mcpxxx with install.sh... it's giving me a bunch of issues. Any ideas? (try it on your OSX prefix, and Linux if you have one)

**Comment by feilen** [comment]
Seems like EntityRenderer.java didn't get patched right. I found an extra copy of a correctly patched version and that fixed it. I think I'll just always keep a working backup of mcpxxx for now :P
