### ISSUE TITLE
Arrows are fired in 'body direction' not cursor direction

### ISSUE THREAD

**Issue by feilen** [mabrowning/minecrift#141]
Pretty much as the title says. You can't aim up/down, and you have to use the keyhole to drag your viewport in order to aim it horizontally.

**Comment by StellaArtois** [comment]
Ok, that's big time broken then....

**Comment by StellaArtois** [comment]
Have a look in com.mtbs.minecrift.control.aim - that may be the culprit (or
a good starting point).

**Comment by feilen** [comment]
Oh! Hey! So, my fix for the crosshair being the thing you walk towards with
decouple move/aim fixes arrows too!

I guess I must have been wrong about pitch then, as that works too.

**Comment by feilen** [comment]
Aaaah that's what it was. Pitch for arrows is currently determined by your
camera pitch, regardless of move/aim settings.

**Comment by feilen** [comment]
With #142 arrow yaw is determined by the 'decoupling' setting, and pitch is always determined by cursor position.
