### ISSUE TITLE
Malformed patch on Mac OS 10.9.5 (branch patch_to_1_8_1)

### ISSUE THREAD

**Issue by Reinforcements** [mabrowning/minecrift#145]
While running the "install.sh", I see this in the patcher.

```
patching file net/minecraft/client/renderer/BlockFluidRenderer.java
patching file net/minecraft/client/renderer/BlockModelRenderer.java
patching file net/minecraft/client/renderer/EntityRenderer.java
patch: **** malformed patch at line 2329: +    

patching file net/minecraft/client/renderer/ImageBufferDownload.java
patching file net/minecraft/client/renderer/ItemRenderer.java
patching file net/minecraft/client/renderer/OpenGlHelper.java
patching file net/minecraft/client/renderer/RenderGlobal.java
```

I suspect this is why I'm getting errors in Eclipse such as ``startCalibration() not found for class EntityRenderer`` (which happens to originate in the file that was patched with the malformed patch, aka, EntityRenderer.java) There are also a lot of other things not found in EntityRender that are causing a lot of other errors.

**Comment by StellaArtois** [comment]
This was introduced on a previous pull request. Should be fixed now; let me know if it isn’t.

**Comment by Reinforcements** [comment]
It's fixed, thanks!

**Comment by StellaArtois** [comment]
Good!
