### ISSUE TITLE
IExtendedEntityProperties crash

### ISSUE THREAD

**Issue by Dasfaust** [mabrowning/minecrift#151]
Hi, it seems the 1.7.10 R1 release has an incompatibility with mods that use the function net.minecraft.entity.player.EntityPlayer.getExtendedProperties(). I don't really know enough about Minecrift to offer any insight, but it seems the method is getting left out somewhere along the line. Mods that use getExtendedProperties() will throw a NoSuchMethodError exception. Here's a crash log with only Minecrift/Forge 1448 and [Witchery](http://minecraft.curseforge.com/mc-mods/69673-witchery). Happens when logging into a server or loading a single player world.

http://puu.sh/iogjR/4d1d6e69dd.txt

**Comment by StellaArtois** [comment]
Ok, many thanks for the detailed report, I'll take a look.

**Comment by StellaArtois** [comment]
Should be sorted next build. Well, it gets to load the world now anyhow! Will fix up a few more Forge issues before I put out a patch release (R1a)
