### ISSUE TITLE
Setting up a Minecrift Server

### ISSUE THREAD

**Issue by DrHibbitts** [mabrowning/minecrift#167]
Tried generating a server install of Minecrift but had issues, I tried modifying the install.py to decompile the server jar instead of the client jar but had a ton of issues.

What is the recommended procedure for building a server for Minecrift?

**Comment by mabrowning** [comment]
Minecrift can be used with a vanilla server; it adds no special network features.

If you run it through forge, you can use a stock forge server.

**Comment by DrHibbitts** [comment]
Hi Mark,

The Vive fork will not allow teleport on the server, it says you need to
get the server to run the same version of the minecrift fork. I couldn't
find any contact details for the fork's developer so I tried seeing if you
had come across similar in the main branch?

Dave

**Comment by mabrowning** [comment]
Ah! You may be looking for https://github.com/Automat-GH/minecrift then. He has really hacked up the minecraft code and may be able to help more.

**Comment by DrHibbitts** [comment]
Yep, that's the fork but sadly you can't log issues on there by the looks
of things and the username is too generic for me to drum up a twitter or
reddit account I could message them on. It seems like it should be a case
of decompiling the server jar, applying the same patches and you're done
but I'm not familiar with MCP and can't figure out how to build the server
jar.

I can do recompile.py --server and reobfuscate.py but both the jars created
aren't able to launch a server so I feel I'm missing somthing. I know Java
and Python well but I'm new to Minecraft (I'm a Vive developer so was just
playing around) so there's probably something minecraft specific I need.

Any ideas? Either of how to get in touch with Automat-GH or on places to
look for building a valid server.jar from the patched files?

Thanks again,
Dave

**Comment by mabrowning** [comment]
Oh, indeed, he has Issues disabled.

Sadly, I don't have any contact information for him, nor any experience with his modifications. We've never attempted to build a server release on the main branch here; our build tools don't have a happy path for that.

Here's a maybe-will-work process:

download mcp, download the correct server.jar, mcp/decompile.sh, ./applychanges.sh, mcp/recompile.sh

The install.sh and build.sh scripts in the minecrifit repo apply OptiFine to the jar before decompiling, which shouldn't really be done for a server.jar. You may get partial patch application failure as the client patches kind of depend on OptiFine being in-place.

**Comment by DrHibbitts** [comment]
No worries, cheers for having a think! I tried something very similar, but
the recompile --server generates a jar I can't run.

I'll keep tinkering, there should be an easy solution for this somewhere I
just don't know where it is yet. If I figure it out I'll try get a build
server script set up and feed it back to  you incase you want to do
anything with it in the future.

Do you have any plans for Vive support on the main branch at some point?
It's gotta be said it works amazingly well. There's something so satisfying
about walking around and physically smashing blocks with your controller!

**Comment by StellaArtois** [comment]
I'll back port it in at some point soon.

**Comment by DrHibbitts** [comment]
Thanks! I'll definitely keep an eye on the project <3

**Comment by StellaArtois** [comment]
I'll have a go at getting the server path running in the install scripts and the installer at some point too.

**Comment by DrHibbitts** [comment]
If you get it running and you're ever in London, I owe  you a drink!

Trying to get the jars to work stole hours of my life. I practically ended
up dreaming in java last night :(
