### ISSUE TITLE
Cursor (not mouse) drift in UI

### ISSUE THREAD

**Issue by BigTwisty** [mabrowning/minecrift#176]
In all GUI's (game menu, crafting GUI, etc.) the cursor constantly moves to the left quickly, stopping at the edge of the screen/GUI.  On slight mouse move the cursor jumps to the actual mouse position and starts traveling to the left again.  On mouse click, the cursor jumps back to position, clicks whatever (item, button, etc.) and starts drifting left again.

This does not affect regular game motion.  Cursor acts just fine when moving in world.

Using the R3 release with Forge.  No other mods loaded at this time.

**Comment by StellaArtois** [comment]
Make sure any other controllers are disconnected currently.

**Comment by BigTwisty** [comment]
Thanks.  I had unplugged all my joysticks, but left the receiver for the XBox One controller plugged in.  I'm not sure why that made a difference, but it did.

This is a great mod!
