### ISSUE TITLE
Sticky trigger (dominant Hand/action hand)

### ISSUE THREAD

**Issue by bknie1** [mabrowning/minecrift#177]
Hi all! Love the mod. My left hand/dominant (action, placement, stacking items) trigger sometimes 'sticks'. That is, if I use the trigger, I may continue to attack/hit a block and I'll have to hit trigger again to stop it from occurring. If I try to move a stack I sometimes end up 'painting' my inventory with the material; every cell I move over gets a piece of material.

I didn't see a similar issue posted but if it was named something other than "trigger" please feel free to close this!

I will try to post a video of this later.

Specs:
Hardware: i7 with a 870m GPU. 16 GB RAM. (I don't think this is a hardware issue, but just for posterity)
VR Hardware: HTC Vive
Software: Windows 10
Minecraft Version: 1.6.61
Profile: Minecrift-Vive 1.7.10 Forge

I'm not using any other mods; it's otherwise a vanilla experience.

Again, thank you for your hard work. I know Java but I've never done any Minecraft modding else I would try to figure it out myself.

**Comment by mabrowning** [comment]
It may sound silly, but do you have "Touchscreen mode" enabled in the
vanilla minecraft options? I remember this option having the effect you
described and I pulled my hair out in frustration until I figured it out...

**Comment by bknie1** [comment]
Hey! Thanks for the suggestion. I do not have Touchscreen controls enabled but turning it on did yield a similar effect; albeit to a greater extent. My touchscreen controls were off, though. We can rule it out. 

I'm going to try disabling my touch pad. Maybe that's messing with it because you can still use a mouse interface to navigate the VR version.

**Comment by bknie1** [comment]
Update: It may have been a tracking issue. After running room config a few more times and tinkering with my lighthouses it seems to have passed for the moment. Odd that it only effected one trigger on one controller, though.
