### ISSUE TITLE
Allow selection of different lens cups

### ISSUE THREAD

**Issue by Paethon** [mabrowning/minecrift#43]
At the moment there seems to be no option to set the lens cup that is being used. 
When using lens cup C this leads to strong distortions that are pretty disorienting.

**Comment by bullfrogberry** [comment]
I agree I feel the screen and gui menu is always curved. I am using VR box with my note 2.

**Comment by SydneyMakers** [comment]
fun fact bullfrogberry, the Oculus DK2 uses the Note 3 screen, with touch sensor intact. you could literally use it as a replacement screen for a note 3

**Comment by bullfrogberry** [comment]
Is there a way to change the two screens to not be wrapped? Is there a way to make the screen have less curving?  As a stated above I an using Trinus VR to stream though usb to my phone with head tracking. But the curved screen is specifically for the rift. Is there a setting I am not seeing?

Thanks

**Comment by Paethon** [comment]
I am going to close this now. With the new VR headsets this is not really relevant anymore
